---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
```{r echo=TRUE}
data.raw <- read.csv(unz('activity.zip','activity.csv'))
data <- na.omit(data.raw)
steps <- data$steps
date <- data$date
data$interval_revised <- sprintf("%04d", data$interval)
data$interval_time <- strptime(data$interval_revised, format = "%H%M")
```
## What is mean total number of steps taken per day?
```{r echo=TRUE}
# histogram
total <- aggregate(steps ~ date, data= data,sum)
hist(total$steps,main ='Histogram of the total number of steps taken each day',xlab ='total number of steps ')

# mean and median of total number of steps taken per day
summary(total)
mean(total$steps,na.rm = TRUE)
median(total$steps,na.rm = TRUE)
```
## What is the average daily activity pattern?
```{r}
aves <- aggregate(data[,1],list(data$interval),mean)
library(ggplot2)
g1 <- ggplot(aves,aes(aves$Group.1,aves$x))+geom_line() +xlab("Time interval(minutes)") + ylab("Average Steps") +list()
g1 + labs(title = "Average daily activity pattern") 
# from the plot, we can see that  835-840 min contains the maximum number of steps. 
```
## Imputing missing values
```{r}
# the total number of rows with NAs
length(which(is.na(data.raw)))
# filling in all of the missing values
d <- cbind(x = data.raw,y = aves)
d$x.steps[is.na(d$x.steps)] <- d$y.x[is.na(d$x.steps)]  
data.new <- d[,1:3]
# new result
total.new <- aggregate(data.new$x.steps ~ data.new$x.date, data= data.new,sum)
names(total.new) <- c("date","Newsteps")
hist(x = total.new$Newsteps,main ='Histogram of the total number of steps taken each day',xlab ='total number of steps ')
summary(total.new)
mean(total.new$Newsteps,na.rm = TRUE)
median(total.new$Newsteps,na.rm = TRUE)

```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
Sys.setlocale("LC_TIME","us")
library(timeDate)
data.new$dayType <- "weekdays" 
data.new$dayType[isWeekend(data.new$x.date)] <- "weekend"

weekend <- data.new[isWeekend(data.new$x.date),]
weekday <- data.new[!isWeekend(data.new$x.date),]
aves.weekdays <- aggregate(weekday[,1],list(weekday$x.interval),mean)
aves.weekends <- aggregate(weekend[,1],list(weekend$x.interval),mean)
weekdays <- data.frame(time = data$interval_time[1:288], ave_steps = aves.weekdays, day = "weekdays")
weekend <- data.frame(time = data$interval_time[1:288], ave_steps = aves.weekends, day = "weekend")
pattern <- rbind(weekdays, weekend)
library(scales)
p <- ggplot(pattern, aes(time, ave_steps.x,group = day))
p + geom_line(aes(colour = day), size = .7) + labs(x = "Interval", y="Number of steps", title = "Average daily activity pattern")+scale_x_datetime(labels= date_format("%H:%M"))  
```